"""Audit changes to test table

Revision ID: c03c47b79258
Revises: 1992be99c9ec
Create Date: 2019-04-07 02:39:38.857101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03c47b79258'
down_revision = '1992be99c9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_audit',
    sa.Column('audit_operation', sa.String(length=1), nullable=False),
    sa.Column('audit_operation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    schema='public'
    )
    op.execute("CREATE OR REPLACE FUNCTION public_test_audit() RETURNS TRIGGER AS $public_test_audit$\nBEGIN\n    \n\n    IF (TG_OP = 'DELETE') THEN\n        INSERT INTO public.test_audit (audit_operation, audit_operation_timestamp, id, name) SELECT 'D', now(), OLD.id, OLD.name;\n    ELSIF (TG_OP = 'UPDATE') THEN\n        INSERT INTO public.test_audit (audit_operation, audit_operation_timestamp, id, name) SELECT 'U', now(), NEW.id, NEW.name;\n    ELSIF (TG_OP = 'INSERT') THEN\n        INSERT INTO public.test_audit (audit_operation, audit_operation_timestamp, id, name) SELECT 'I', now(), NEW.id, NEW.name;\n    END IF;\n    RETURN NULL; -- result is ignored since this is an AFTER trigger\nEND;\n$public_test_audit$ LANGUAGE plpgsql;\n\nDROP TRIGGER IF EXISTS public_test_audit ON public.test;\n\nCREATE TRIGGER public_test_audit\nAFTER INSERT OR UPDATE OR DELETE ON public.test\nFOR EACH ROW EXECUTE PROCEDURE public_test_audit();\n")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS public_test_audit ON public.test;\nDROP FUNCTION IF EXISTS public_test_audit;\n')
    op.drop_table('test_audit', schema='public')
    # ### end Alembic commands ###
